// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.1
// source: prattle.proto

package server

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ProxyClient is the client API for Proxy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProxyClient interface {
	// Signup accepts a new password and mints a new ID and OTP seed
	Signup(ctx context.Context, in *SignupRequest, opts ...grpc.CallOption) (*SignupResponse, error)
	// Finalise is used to finalise the signup flow, which it does by accepting
	// the minted ID and a valid OTP value.
	//
	// This call will return an error or nothing
	Finalise(ctx context.Context, in *OTPAndKey, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Token accepts a password and a valid OTP value, returning a new bearer
	// token which can be used in Subscribing to message stream
	Token(ctx context.Context, in *OTPAndKey, opts ...grpc.CallOption) (*OTPAndKey, error)
	// AddPublicKey adds a new public key for a user. A user can have up to n public
	// keys, where n is configured on the proxy.
	//
	// Where n is too few, a user is limited by the number of clients they can connect
	// with.
	// Where n is too high, the cost of sending a user a message becomes high, as does
	// receiving _for_ that user
	AddPublicKey(ctx context.Context, in *OTPAndKey, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Subscribe is used to provide a stream to receive a user's messages
	Subscribe(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (Proxy_SubscribeClient, error)
	// PublicKey retrieves the public key of a user, handling cases where a key
	// lives on a third-party proxy instance
	PublicKey(ctx context.Context, in *OTPAndKey, opts ...grpc.CallOption) (*OTPAndKey, error)
	// Send accepts an encoded/ wrapped message and sends it to a user
	Send(ctx context.Context, in *MessageWrapper, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type proxyClient struct {
	cc grpc.ClientConnInterface
}

func NewProxyClient(cc grpc.ClientConnInterface) ProxyClient {
	return &proxyClient{cc}
}

func (c *proxyClient) Signup(ctx context.Context, in *SignupRequest, opts ...grpc.CallOption) (*SignupResponse, error) {
	out := new(SignupResponse)
	err := c.cc.Invoke(ctx, "/Proxy/Signup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyClient) Finalise(ctx context.Context, in *OTPAndKey, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/Proxy/Finalise", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyClient) Token(ctx context.Context, in *OTPAndKey, opts ...grpc.CallOption) (*OTPAndKey, error) {
	out := new(OTPAndKey)
	err := c.cc.Invoke(ctx, "/Proxy/Token", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyClient) AddPublicKey(ctx context.Context, in *OTPAndKey, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/Proxy/AddPublicKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyClient) Subscribe(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (Proxy_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &Proxy_ServiceDesc.Streams[0], "/Proxy/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &proxySubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Proxy_SubscribeClient interface {
	Recv() (*MessageWrapper, error)
	grpc.ClientStream
}

type proxySubscribeClient struct {
	grpc.ClientStream
}

func (x *proxySubscribeClient) Recv() (*MessageWrapper, error) {
	m := new(MessageWrapper)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *proxyClient) PublicKey(ctx context.Context, in *OTPAndKey, opts ...grpc.CallOption) (*OTPAndKey, error) {
	out := new(OTPAndKey)
	err := c.cc.Invoke(ctx, "/Proxy/PublicKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyClient) Send(ctx context.Context, in *MessageWrapper, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/Proxy/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProxyServer is the server API for Proxy service.
// All implementations must embed UnimplementedProxyServer
// for forward compatibility
type ProxyServer interface {
	// Signup accepts a new password and mints a new ID and OTP seed
	Signup(context.Context, *SignupRequest) (*SignupResponse, error)
	// Finalise is used to finalise the signup flow, which it does by accepting
	// the minted ID and a valid OTP value.
	//
	// This call will return an error or nothing
	Finalise(context.Context, *OTPAndKey) (*emptypb.Empty, error)
	// Token accepts a password and a valid OTP value, returning a new bearer
	// token which can be used in Subscribing to message stream
	Token(context.Context, *OTPAndKey) (*OTPAndKey, error)
	// AddPublicKey adds a new public key for a user. A user can have up to n public
	// keys, where n is configured on the proxy.
	//
	// Where n is too few, a user is limited by the number of clients they can connect
	// with.
	// Where n is too high, the cost of sending a user a message becomes high, as does
	// receiving _for_ that user
	AddPublicKey(context.Context, *OTPAndKey) (*emptypb.Empty, error)
	// Subscribe is used to provide a stream to receive a user's messages
	Subscribe(*emptypb.Empty, Proxy_SubscribeServer) error
	// PublicKey retrieves the public key of a user, handling cases where a key
	// lives on a third-party proxy instance
	PublicKey(context.Context, *OTPAndKey) (*OTPAndKey, error)
	// Send accepts an encoded/ wrapped message and sends it to a user
	Send(context.Context, *MessageWrapper) (*emptypb.Empty, error)
	mustEmbedUnimplementedProxyServer()
}

// UnimplementedProxyServer must be embedded to have forward compatible implementations.
type UnimplementedProxyServer struct {
}

func (UnimplementedProxyServer) Signup(context.Context, *SignupRequest) (*SignupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Signup not implemented")
}
func (UnimplementedProxyServer) Finalise(context.Context, *OTPAndKey) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Finalise not implemented")
}
func (UnimplementedProxyServer) Token(context.Context, *OTPAndKey) (*OTPAndKey, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Token not implemented")
}
func (UnimplementedProxyServer) AddPublicKey(context.Context, *OTPAndKey) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPublicKey not implemented")
}
func (UnimplementedProxyServer) Subscribe(*emptypb.Empty, Proxy_SubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedProxyServer) PublicKey(context.Context, *OTPAndKey) (*OTPAndKey, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublicKey not implemented")
}
func (UnimplementedProxyServer) Send(context.Context, *MessageWrapper) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedProxyServer) mustEmbedUnimplementedProxyServer() {}

// UnsafeProxyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProxyServer will
// result in compilation errors.
type UnsafeProxyServer interface {
	mustEmbedUnimplementedProxyServer()
}

func RegisterProxyServer(s grpc.ServiceRegistrar, srv ProxyServer) {
	s.RegisterService(&Proxy_ServiceDesc, srv)
}

func _Proxy_Signup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServer).Signup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Proxy/Signup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServer).Signup(ctx, req.(*SignupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Proxy_Finalise_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OTPAndKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServer).Finalise(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Proxy/Finalise",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServer).Finalise(ctx, req.(*OTPAndKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _Proxy_Token_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OTPAndKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServer).Token(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Proxy/Token",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServer).Token(ctx, req.(*OTPAndKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _Proxy_AddPublicKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OTPAndKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServer).AddPublicKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Proxy/AddPublicKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServer).AddPublicKey(ctx, req.(*OTPAndKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _Proxy_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProxyServer).Subscribe(m, &proxySubscribeServer{stream})
}

type Proxy_SubscribeServer interface {
	Send(*MessageWrapper) error
	grpc.ServerStream
}

type proxySubscribeServer struct {
	grpc.ServerStream
}

func (x *proxySubscribeServer) Send(m *MessageWrapper) error {
	return x.ServerStream.SendMsg(m)
}

func _Proxy_PublicKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OTPAndKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServer).PublicKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Proxy/PublicKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServer).PublicKey(ctx, req.(*OTPAndKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _Proxy_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageWrapper)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Proxy/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServer).Send(ctx, req.(*MessageWrapper))
	}
	return interceptor(ctx, in, info, handler)
}

// Proxy_ServiceDesc is the grpc.ServiceDesc for Proxy service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Proxy_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Proxy",
	HandlerType: (*ProxyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Signup",
			Handler:    _Proxy_Signup_Handler,
		},
		{
			MethodName: "Finalise",
			Handler:    _Proxy_Finalise_Handler,
		},
		{
			MethodName: "Token",
			Handler:    _Proxy_Token_Handler,
		},
		{
			MethodName: "AddPublicKey",
			Handler:    _Proxy_AddPublicKey_Handler,
		},
		{
			MethodName: "PublicKey",
			Handler:    _Proxy_PublicKey_Handler,
		},
		{
			MethodName: "Send",
			Handler:    _Proxy_Send_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _Proxy_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "prattle.proto",
}
