name: CI

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Generate stuff
      run: |
        make

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: gosec
      run: |
        go install github.com/securego/gosec/v2/cmd/gosec@latest
        gosec .

    - name: golangci-lint
      run: |
        go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.43.0
        golangci-lint run --skip-files='.*_test.go' --disable=errcheck

    - name: gokart
      run: |
        go install github.com/praetorian-inc/gokart@latest
        gokart scan
